### ISSUE TITLE
Left-Padding or  / fixed width for statusbar item

### ISSUE THREAD

**Issue by chrisgrieser** [spslater/obsidian-cursor-location-plugin#14]
Only a minor visual thing, but when moving from line 9 to 10 (or line 99 to 100), the statusbar item changes its width, and consequently pushes all other statusbar items to the left, which looks a bit glitchy. Same thing for the column number

Could the plugin maybe add some padding to the left, to prevent this behavior?

**Comment by spslater** [comment]
This is a good idea, I'll probably add this as a non-default setting. One issue I immediately know of is that multiple space characters will get squashed automatically by HTML.

I have found a small way around that possibly (in the couple minutes of tinkering I have done) but it still causes the shift when going from 9 to 10 (or 99 to 100) because the space isn't as wide as the characters. 

I could set it to a monospace font but then it doesn't match the rest of the status bar. (This would be a last resort if nothing else works)

I think there might be a way I make it a fixed width element and have it update when it goes from needing 1 digit to 2 (or 2->3, ect, ect)

I will dig into this more in the next few days, as I have time.

**Comment by spslater** [comment]
After trying to figure things out a couple different ways, I haven't been able to figure out an eloquent way to make this work. I'm able to get it to work for a single cursor without highlighting anything. Though it's not perfect.
- There's still jumps in width when getting to certain places in the document
- Once you start adding a second cursor or highlight some text, it causes the padding to account for the maximum possible causes a bunch of blank space to appear and it's not pretty

I'm gonna put this on the back burner for right now, not actively working on it, but keeping it noodling around in the back of my head.

**Comment by chrisgrieser** [comment]
Hmm, so I had the idea to do this with a relatively simple css fix maybe:

```css
.status-bar-item.plugin-obsidian-cursor-location-plugin {
	min-width: 4ch;
}
```

It uses a minimum width, as the status bar item becomes much longer when you have selections, where the change is okay. But the minimum width ensures that without a selection, the size should not glitch too much.

Also, using `ch` as unit since it is relative to the glyph, the width adapts to theme's changing the sizing of the status bar (to a degree).

**Comment by spslater** [comment]
Interesting, I will try this and see how this looks! Good thinking.

**Comment by spslater** [comment]
I will get this added to the next release, I want to include #15 as well as clean up the settings.
