### ISSUE TITLE
Freeze on tab close/switch

### ISSUE THREAD

**Issue by simonSlamka** [spslater/obsidian-cursor-location-plugin#21]
Closing a tab or switching between open tabs freezes the editor while this plugin is enabled. I tried looking at the console, but there's no useful output regarding the issue (to my non-web dev eyes).

Repro is simple - install, enable, and try closing an open tab or switching to another one.

**Comment by spslater** [comment]
I have not been able to reproduce this. I've just updated Obsidian to 1.3.5 and I am not getting any freezing when I switch tabs or close a tab (both the selected tab and another tab). 
* What other plugins do you have enabled and installed?
* What are you current settings for the plugin?

**Comment by bb010g** [comment]
The loop I'm getting is: `app.workspace.setActiveLeaf` → `app.workspace.requestActiveLeafEvents` →  → `CursorLocation.updateShowStatus()` → `app.workspace.getLeaf()` → `app.workspace.getUnpinnedLeaf()` → `app.workspace.getMostRecentLeaf(app.workspace.activeLeaf.getContainer()).parent.insertChild(-1, new WorkspaceLeaf(app))` (`WorkspaceTabs.insertChild`) → `(….parent:super).insertChild` (`WorkspaceParent.insertChild`) → `….parent.workspace.onLayoutChange(….parent)` → `app.workspace.requestUpdateLayout(Workspace.updateLayout)` → `var skipUpdateLayout = false, myWorkspace = app.workspace, myArguments = arguments, doUpdateLayout = function() { skipUpdateLayout = false; var myWorkspaceTmp = myWorkspace, myArgumentsTmp = myArguments; myWorkspace = null, myArguments = null, Workspace.updateLayout.apply(myWorkspaceTmp, myArguments); }; skipUpdateLayout || (skipUpdateLayout = true, window.queueMicrotask(doUpdateLayout))` → \[later Node.js microtask callback execution\] → `app.workspace.requestUpdateLayout:doUpdateLayout` → `app.workspace.updateLayout()` → `app.workspace.trigger("layout-change")` → `app.workspace.super.trigger("layout-change")` (`Event.trigger`) → `app.workspace.super.tryTrigger` → `(CursorLocation.onload:onLayoutChange)()` → looping from previous `CursorLocation.updateShowStatus()`.

**Comment by bb010g** [comment]
>     * What other plugins do you have enabled and installed?
> 
>     * What are you current settings for the plugin?

I can reproduce this with no other plugins enabled upon switching to a pinned tab in any position. This failure should be independent of settings, given the execution path. When switching into an unpinned tab, the `app.workspace.getUnpinnedLeaf()` flow still triggers, but `app.workspace.activeLeaf.canNavigate()` is `true` so `app.workspace.activeLeaf` gets returned early. When switching into a pinned tab, `app.workspace.getUnpinnedLeaf()` wants to find a leaf where (at least) `.canNavigate()` and `.parent.children[.currentTab] === .` but fails due to the current tab (a pinned tab) failing `.canNavigate()`. To solve this, `getUnpinnedLeaf` calls `.insertChild` on the most recent leaf in the workspace's active leaf's container (basically, inserting a sibling to the active leaf), but this insertion calls `workspace.onLayoutChange` and we call `workspace.getLeaf()` and we're looping. It looks like `Workspace.getLeaf()` is not the function you want.

Here's its definition:

```js
t.prototype.getLeaf = function(e, t) {
    return "split" === e ? this.splitActiveLeaf(t) : "tab" === e || !0 === e ? this.createLeafInTabGroup() : "window" === e ? this.openPopoutLeaf() : this.getUnpinnedLeaf()
}
```

See also [`Workspace.getLeaf() method`](https://docs.obsidian.md/Reference/TypeScript+API/Workspace/getLeaf) in the developer documentation:

> Creates a new leaf in a leaf adjacent to the currently active leaf. If direction is `'vertical'`, the leaf will appear to the right. If direction is `'horizontal'`, the leaf will appear below the current leaf.

[`Workspace.activeLeaf` property] points us at an alternative:

> > Warning: This API is now obsolete.
> >
> > - The use of this field is discouraged.
>
> Indicates the currently focused leaf, if one exists.
>
> Please avoid using `activeLeaf` directly, especially without checking whether `activeLeaf` is null.
>
> The recommended alternatives are:
> - If you need information about the current view, use [`Workspace.getActiveViewOfType`](https://docs.obsidian.md/Reference/TypeScript+API/Workspace/getActiveViewOfType).
> - If you need to open a new file or navigate a view, use [`Workspace.getLeaf`](https://docs.obsidian.md/Reference/TypeScript+API/Workspace/getLeaf).

All we want in `CursorLocation.updateShowStatus()` is the active leaf's mode, so `this.app.workspace.getActiveViewOfType(obsidian.View).getState()` should do just fine there, and it does in testing. I'll open a PR.

**Comment by spslater** [comment]
Awesome, that will fix the issue! Pinning a tab is what got me to see the issue as well. Thanks for getting on that so quickly. Just a few small changes needed in that PR and then I will happily merge it.

**Comment by simonSlamka** [comment]
Ah, yes. I missed the fact that I also experienced this with a pinned tab. Apologies!

**Comment by bb010g** [comment]
> Just a few small changes needed in that PR and then I will happily merge it.

@spslater If you're waiting on me to make them, I have no idea what the changes you need are.

**Comment by spslater** [comment]
No worries, I've been traveling for a couple weeks, I'll be able to get the fix pushed when I get home in a couple days.

**Comment by swar8080** [comment]
Thanks @bb010g for diving into the obsidian source code and debugging this. I tested your pull request and it unblocks people wanting to use this plugin and the Plugin Update Tracker, which also makes changes to active leafs: https://github.com/swar8080/obsidian-plugin-update-tracker/issues/60

**Comment by huyz** [comment]
Yay, I can finally upgrade from Obsidian 1.2.8 to 1.3.5!
